/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.impl;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.18.1)", date = "2023-06-21")
public class Book implements org.apache.thrift.TBase<Book, Book._Fields>, java.io.Serializable, Cloneable, Comparable<Book> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Book");

  private static final org.apache.thrift.protocol.TField BOOK_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("bookId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField BOOK_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("bookName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField BOOK_AUTHOR_FIELD_DESC = new org.apache.thrift.protocol.TField("bookAuthor", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new BookStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new BookTupleSchemeFactory();

  public int bookId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String bookName; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String bookAuthor; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BOOK_ID((short)1, "bookId"),
    BOOK_NAME((short)2, "bookName"),
    BOOK_AUTHOR((short)3, "bookAuthor");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BOOK_ID
          return BOOK_ID;
        case 2: // BOOK_NAME
          return BOOK_NAME;
        case 3: // BOOK_AUTHOR
          return BOOK_AUTHOR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __BOOKID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BOOK_ID, new org.apache.thrift.meta_data.FieldMetaData("bookId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.BOOK_NAME, new org.apache.thrift.meta_data.FieldMetaData("bookName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BOOK_AUTHOR, new org.apache.thrift.meta_data.FieldMetaData("bookAuthor", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Book.class, metaDataMap);
  }

  public Book() {
  }

  public Book(
    int bookId,
    java.lang.String bookName,
    java.lang.String bookAuthor)
  {
    this();
    this.bookId = bookId;
    setBookIdIsSet(true);
    this.bookName = bookName;
    this.bookAuthor = bookAuthor;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Book(Book other) {
    __isset_bitfield = other.__isset_bitfield;
    this.bookId = other.bookId;
    if (other.isSetBookName()) {
      this.bookName = other.bookName;
    }
    if (other.isSetBookAuthor()) {
      this.bookAuthor = other.bookAuthor;
    }
  }

  @Override
  public Book deepCopy() {
    return new Book(this);
  }

  @Override
  public void clear() {
    setBookIdIsSet(false);
    this.bookId = 0;
    this.bookName = null;
    this.bookAuthor = null;
  }

  public int getBookId() {
    return this.bookId;
  }

  public Book setBookId(int bookId) {
    this.bookId = bookId;
    setBookIdIsSet(true);
    return this;
  }

  public void unsetBookId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BOOKID_ISSET_ID);
  }

  /** Returns true if field bookId is set (has been assigned a value) and false otherwise */
  public boolean isSetBookId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BOOKID_ISSET_ID);
  }

  public void setBookIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BOOKID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getBookName() {
    return this.bookName;
  }

  public Book setBookName(@org.apache.thrift.annotation.Nullable java.lang.String bookName) {
    this.bookName = bookName;
    return this;
  }

  public void unsetBookName() {
    this.bookName = null;
  }

  /** Returns true if field bookName is set (has been assigned a value) and false otherwise */
  public boolean isSetBookName() {
    return this.bookName != null;
  }

  public void setBookNameIsSet(boolean value) {
    if (!value) {
      this.bookName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getBookAuthor() {
    return this.bookAuthor;
  }

  public Book setBookAuthor(@org.apache.thrift.annotation.Nullable java.lang.String bookAuthor) {
    this.bookAuthor = bookAuthor;
    return this;
  }

  public void unsetBookAuthor() {
    this.bookAuthor = null;
  }

  /** Returns true if field bookAuthor is set (has been assigned a value) and false otherwise */
  public boolean isSetBookAuthor() {
    return this.bookAuthor != null;
  }

  public void setBookAuthorIsSet(boolean value) {
    if (!value) {
      this.bookAuthor = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case BOOK_ID:
      if (value == null) {
        unsetBookId();
      } else {
        setBookId((java.lang.Integer)value);
      }
      break;

    case BOOK_NAME:
      if (value == null) {
        unsetBookName();
      } else {
        setBookName((java.lang.String)value);
      }
      break;

    case BOOK_AUTHOR:
      if (value == null) {
        unsetBookAuthor();
      } else {
        setBookAuthor((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case BOOK_ID:
      return getBookId();

    case BOOK_NAME:
      return getBookName();

    case BOOK_AUTHOR:
      return getBookAuthor();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case BOOK_ID:
      return isSetBookId();
    case BOOK_NAME:
      return isSetBookName();
    case BOOK_AUTHOR:
      return isSetBookAuthor();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof Book)
      return this.equals((Book)that);
    return false;
  }

  public boolean equals(Book that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_bookId = true;
    boolean that_present_bookId = true;
    if (this_present_bookId || that_present_bookId) {
      if (!(this_present_bookId && that_present_bookId))
        return false;
      if (this.bookId != that.bookId)
        return false;
    }

    boolean this_present_bookName = true && this.isSetBookName();
    boolean that_present_bookName = true && that.isSetBookName();
    if (this_present_bookName || that_present_bookName) {
      if (!(this_present_bookName && that_present_bookName))
        return false;
      if (!this.bookName.equals(that.bookName))
        return false;
    }

    boolean this_present_bookAuthor = true && this.isSetBookAuthor();
    boolean that_present_bookAuthor = true && that.isSetBookAuthor();
    if (this_present_bookAuthor || that_present_bookAuthor) {
      if (!(this_present_bookAuthor && that_present_bookAuthor))
        return false;
      if (!this.bookAuthor.equals(that.bookAuthor))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + bookId;

    hashCode = hashCode * 8191 + ((isSetBookName()) ? 131071 : 524287);
    if (isSetBookName())
      hashCode = hashCode * 8191 + bookName.hashCode();

    hashCode = hashCode * 8191 + ((isSetBookAuthor()) ? 131071 : 524287);
    if (isSetBookAuthor())
      hashCode = hashCode * 8191 + bookAuthor.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Book other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetBookId(), other.isSetBookId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBookId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bookId, other.bookId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBookName(), other.isSetBookName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBookName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bookName, other.bookName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBookAuthor(), other.isSetBookAuthor());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBookAuthor()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bookAuthor, other.bookAuthor);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Book(");
    boolean first = true;

    sb.append("bookId:");
    sb.append(this.bookId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("bookName:");
    if (this.bookName == null) {
      sb.append("null");
    } else {
      sb.append(this.bookName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("bookAuthor:");
    if (this.bookAuthor == null) {
      sb.append("null");
    } else {
      sb.append(this.bookAuthor);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BookStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public BookStandardScheme getScheme() {
      return new BookStandardScheme();
    }
  }

  private static class BookStandardScheme extends org.apache.thrift.scheme.StandardScheme<Book> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, Book struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BOOK_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.bookId = iprot.readI32();
              struct.setBookIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BOOK_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.bookName = iprot.readString();
              struct.setBookNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // BOOK_AUTHOR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.bookAuthor = iprot.readString();
              struct.setBookAuthorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, Book struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(BOOK_ID_FIELD_DESC);
      oprot.writeI32(struct.bookId);
      oprot.writeFieldEnd();
      if (struct.bookName != null) {
        oprot.writeFieldBegin(BOOK_NAME_FIELD_DESC);
        oprot.writeString(struct.bookName);
        oprot.writeFieldEnd();
      }
      if (struct.bookAuthor != null) {
        oprot.writeFieldBegin(BOOK_AUTHOR_FIELD_DESC);
        oprot.writeString(struct.bookAuthor);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BookTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public BookTupleScheme getScheme() {
      return new BookTupleScheme();
    }
  }

  private static class BookTupleScheme extends org.apache.thrift.scheme.TupleScheme<Book> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Book struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetBookId()) {
        optionals.set(0);
      }
      if (struct.isSetBookName()) {
        optionals.set(1);
      }
      if (struct.isSetBookAuthor()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetBookId()) {
        oprot.writeI32(struct.bookId);
      }
      if (struct.isSetBookName()) {
        oprot.writeString(struct.bookName);
      }
      if (struct.isSetBookAuthor()) {
        oprot.writeString(struct.bookAuthor);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Book struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.bookId = iprot.readI32();
        struct.setBookIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.bookName = iprot.readString();
        struct.setBookNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.bookAuthor = iprot.readString();
        struct.setBookAuthorIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

