/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.impl;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.18.1)", date = "2023-06-21")
public class LibraryEvent implements org.apache.thrift.TBase<LibraryEvent, LibraryEvent._Fields>, java.io.Serializable, Cloneable, Comparable<LibraryEvent> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LibraryEvent");

  private static final org.apache.thrift.protocol.TField LIBRARY_EVENT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("libraryEventId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField BOOK_FIELD_DESC = new org.apache.thrift.protocol.TField("book", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new LibraryEventStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new LibraryEventTupleSchemeFactory();

  public int libraryEventId; // required
  /**
   * 
   * @see LibraryEventType
   */
  public @org.apache.thrift.annotation.Nullable LibraryEventType type; // required
  public @org.apache.thrift.annotation.Nullable Book book; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LIBRARY_EVENT_ID((short)1, "libraryEventId"),
    /**
     * 
     * @see LibraryEventType
     */
    TYPE((short)2, "type"),
    BOOK((short)3, "book");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LIBRARY_EVENT_ID
          return LIBRARY_EVENT_ID;
        case 2: // TYPE
          return TYPE;
        case 3: // BOOK
          return BOOK;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __LIBRARYEVENTID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LIBRARY_EVENT_ID, new org.apache.thrift.meta_data.FieldMetaData("libraryEventId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("type", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, LibraryEventType.class)));
    tmpMap.put(_Fields.BOOK, new org.apache.thrift.meta_data.FieldMetaData("book", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Book.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LibraryEvent.class, metaDataMap);
  }

  public LibraryEvent() {
  }

  public LibraryEvent(
    int libraryEventId,
    LibraryEventType type,
    Book book)
  {
    this();
    this.libraryEventId = libraryEventId;
    setLibraryEventIdIsSet(true);
    this.type = type;
    this.book = book;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LibraryEvent(LibraryEvent other) {
    __isset_bitfield = other.__isset_bitfield;
    this.libraryEventId = other.libraryEventId;
    if (other.isSetType()) {
      this.type = other.type;
    }
    if (other.isSetBook()) {
      this.book = new Book(other.book);
    }
  }

  @Override
  public LibraryEvent deepCopy() {
    return new LibraryEvent(this);
  }

  @Override
  public void clear() {
    setLibraryEventIdIsSet(false);
    this.libraryEventId = 0;
    this.type = null;
    this.book = null;
  }

  public int getLibraryEventId() {
    return this.libraryEventId;
  }

  public LibraryEvent setLibraryEventId(int libraryEventId) {
    this.libraryEventId = libraryEventId;
    setLibraryEventIdIsSet(true);
    return this;
  }

  public void unsetLibraryEventId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LIBRARYEVENTID_ISSET_ID);
  }

  /** Returns true if field libraryEventId is set (has been assigned a value) and false otherwise */
  public boolean isSetLibraryEventId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LIBRARYEVENTID_ISSET_ID);
  }

  public void setLibraryEventIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LIBRARYEVENTID_ISSET_ID, value);
  }

  /**
   * 
   * @see LibraryEventType
   */
  @org.apache.thrift.annotation.Nullable
  public LibraryEventType getType() {
    return this.type;
  }

  /**
   * 
   * @see LibraryEventType
   */
  public LibraryEvent setType(@org.apache.thrift.annotation.Nullable LibraryEventType type) {
    this.type = type;
    return this;
  }

  public void unsetType() {
    this.type = null;
  }

  /** Returns true if field type is set (has been assigned a value) and false otherwise */
  public boolean isSetType() {
    return this.type != null;
  }

  public void setTypeIsSet(boolean value) {
    if (!value) {
      this.type = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public Book getBook() {
    return this.book;
  }

  public LibraryEvent setBook(@org.apache.thrift.annotation.Nullable Book book) {
    this.book = book;
    return this;
  }

  public void unsetBook() {
    this.book = null;
  }

  /** Returns true if field book is set (has been assigned a value) and false otherwise */
  public boolean isSetBook() {
    return this.book != null;
  }

  public void setBookIsSet(boolean value) {
    if (!value) {
      this.book = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case LIBRARY_EVENT_ID:
      if (value == null) {
        unsetLibraryEventId();
      } else {
        setLibraryEventId((java.lang.Integer)value);
      }
      break;

    case TYPE:
      if (value == null) {
        unsetType();
      } else {
        setType((LibraryEventType)value);
      }
      break;

    case BOOK:
      if (value == null) {
        unsetBook();
      } else {
        setBook((Book)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case LIBRARY_EVENT_ID:
      return getLibraryEventId();

    case TYPE:
      return getType();

    case BOOK:
      return getBook();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case LIBRARY_EVENT_ID:
      return isSetLibraryEventId();
    case TYPE:
      return isSetType();
    case BOOK:
      return isSetBook();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof LibraryEvent)
      return this.equals((LibraryEvent)that);
    return false;
  }

  public boolean equals(LibraryEvent that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_libraryEventId = true;
    boolean that_present_libraryEventId = true;
    if (this_present_libraryEventId || that_present_libraryEventId) {
      if (!(this_present_libraryEventId && that_present_libraryEventId))
        return false;
      if (this.libraryEventId != that.libraryEventId)
        return false;
    }

    boolean this_present_type = true && this.isSetType();
    boolean that_present_type = true && that.isSetType();
    if (this_present_type || that_present_type) {
      if (!(this_present_type && that_present_type))
        return false;
      if (!this.type.equals(that.type))
        return false;
    }

    boolean this_present_book = true && this.isSetBook();
    boolean that_present_book = true && that.isSetBook();
    if (this_present_book || that_present_book) {
      if (!(this_present_book && that_present_book))
        return false;
      if (!this.book.equals(that.book))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + libraryEventId;

    hashCode = hashCode * 8191 + ((isSetType()) ? 131071 : 524287);
    if (isSetType())
      hashCode = hashCode * 8191 + type.getValue();

    hashCode = hashCode * 8191 + ((isSetBook()) ? 131071 : 524287);
    if (isSetBook())
      hashCode = hashCode * 8191 + book.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(LibraryEvent other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetLibraryEventId(), other.isSetLibraryEventId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLibraryEventId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.libraryEventId, other.libraryEventId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetType(), other.isSetType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type, other.type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBook(), other.isSetBook());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBook()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.book, other.book);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("LibraryEvent(");
    boolean first = true;

    sb.append("libraryEventId:");
    sb.append(this.libraryEventId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("type:");
    if (this.type == null) {
      sb.append("null");
    } else {
      sb.append(this.type);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("book:");
    if (this.book == null) {
      sb.append("null");
    } else {
      sb.append(this.book);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (book != null) {
      book.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LibraryEventStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LibraryEventStandardScheme getScheme() {
      return new LibraryEventStandardScheme();
    }
  }

  private static class LibraryEventStandardScheme extends org.apache.thrift.scheme.StandardScheme<LibraryEvent> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, LibraryEvent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LIBRARY_EVENT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.libraryEventId = iprot.readI32();
              struct.setLibraryEventIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.type = com.thrift.impl.LibraryEventType.findByValue(iprot.readI32());
              struct.setTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // BOOK
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.book = new Book();
              struct.book.read(iprot);
              struct.setBookIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, LibraryEvent struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(LIBRARY_EVENT_ID_FIELD_DESC);
      oprot.writeI32(struct.libraryEventId);
      oprot.writeFieldEnd();
      if (struct.type != null) {
        oprot.writeFieldBegin(TYPE_FIELD_DESC);
        oprot.writeI32(struct.type.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.book != null) {
        oprot.writeFieldBegin(BOOK_FIELD_DESC);
        struct.book.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LibraryEventTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LibraryEventTupleScheme getScheme() {
      return new LibraryEventTupleScheme();
    }
  }

  private static class LibraryEventTupleScheme extends org.apache.thrift.scheme.TupleScheme<LibraryEvent> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LibraryEvent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetLibraryEventId()) {
        optionals.set(0);
      }
      if (struct.isSetType()) {
        optionals.set(1);
      }
      if (struct.isSetBook()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetLibraryEventId()) {
        oprot.writeI32(struct.libraryEventId);
      }
      if (struct.isSetType()) {
        oprot.writeI32(struct.type.getValue());
      }
      if (struct.isSetBook()) {
        struct.book.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LibraryEvent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.libraryEventId = iprot.readI32();
        struct.setLibraryEventIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.type = com.thrift.impl.LibraryEventType.findByValue(iprot.readI32());
        struct.setTypeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.book = new Book();
        struct.book.read(iprot);
        struct.setBookIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

